export const INITIALIZE_STORIES = "INITIALIZE_STORIES";
export const INITIALIZE_STORIES_REQUEST = "INITIALIZE_STORIES_REQUEST";
export const INITIALIZE_STORIES_SUCCESS = "INITIALIZE_STORIES_SUCCESS";
export const GET_STORIES = "GET_STORIES";
export const GET_STORIES_SUCCESS = "GET_STORIES_SUCCESS";
export const GET_STORIES_FAILED = "GET_STORIES_FAILED";
